# Configuração de Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/clube_cosmeticos
spring.datasource.username=postgres
spring.datasource.password=luizsql@2006

# O Hibernate vai criar as tabelas automaticamente baseado no nosso código!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true